import type { AssetPriceMap, BankingOverview } from "./types";

export const bankingAssetPrices: AssetPriceMap = {
  USDC: { symbol: "USDC", priceUsd: 1 },
  USDT: { symbol: "USDT", priceUsd: 1 },
  ETH: { symbol: "ETH", priceUsd: 3950.25 },
  BTC: { symbol: "BTC", priceUsd: 118420.6 },
};

export const bankingOverview: BankingOverview = {
  profile: {
    accountName: "Atlas Meridian Holdings",
    accountTier: "Enterprise",
    verificationStatus: "verified",
    relationshipManager: "Amelia Grant",
  },
  totalPortfolioUsd: 284720.44,
  spotBalanceUsd: 205184.2,
  fundingBalanceUsd: 64126.24,
  pendingSettlementUsd: 15410,
  assets: [
    { symbol: "BTC", name: "Bitcoin", location: "spot", amount: 1.1254, priceUsd: 118420.6, usdValue: 133274.54, change24h: 2.41 },
    { symbol: "ETH", name: "Ethereum", location: "spot", amount: 14.823, priceUsd: 3950.25, usdValue: 58553.06, change24h: 1.18 },
    { symbol: "USDC", name: "USD Coin", location: "spot", amount: 13356.6, priceUsd: 1, usdValue: 13356.6, change24h: 0.01 },
    { symbol: "USDC", name: "USD Coin", location: "funding", amount: 52126.24, priceUsd: 1, usdValue: 52126.24, change24h: 0.01 },
    { symbol: "USDT", name: "Tether", location: "funding", amount: 12000, priceUsd: 1, usdValue: 12000, change24h: -0.01 },
  ],
  fiatBalances: [
    { currency: "USD", amount: 64126.24, usdValue: 64126.24, available: 48716.24 },
    { currency: "EUR", amount: 8400, usdValue: 9130.43, available: 8400 },
    { currency: "GBP", amount: 3100, usdValue: 3924.05, available: 3100 },
  ],
  bankAccounts: [
    { id: "bank_us_4821", bankName: "Northstar Commercial Bank", accountName: "Atlas Meridian Holdings", accountType: "Business checking", maskedNumber: "•••• 4821", currency: "USD", country: "United States", status: "verified", isDefault: true },
    { id: "bank_gb_1007", bankName: "Crownfield Bank", accountName: "Atlas Meridian Holdings Ltd", accountType: "Corporate current", maskedNumber: "•••• 1007", currency: "GBP", country: "United Kingdom", status: "verified", isDefault: false },
    { id: "bank_eu_7314", bankName: "Continental Treasury", accountName: "Atlas Meridian Europe", accountType: "Business account", maskedNumber: "•••• 7314", currency: "EUR", country: "Germany", status: "pending", isDefault: false },
  ],
  limits: [
    { label: "Daily bank withdrawal", used: 15410, total: 250000, currency: "USD" },
    { label: "Monthly bank withdrawal", used: 184620, total: 2000000, currency: "USD" },
  ],
  transactions: [
    {
      id: "txn_10482",
      reference: "LNX-BW-10482",
      direction: "spot_to_bank",
      asset: "ETH",
      assetAmount: 3.942,
      fiatCurrency: "USD",
      fiatAmount: 15410,
      feeUsd: 69.13,
      status: "processing",
      destination: "Northstar Commercial •••• 4821",
      createdAt: "2026-07-19T09:42:00.000Z",
      estimatedArrival: "Jul 21, 2026",
      timeline: [
        { label: "Request submitted", timestamp: "Jul 19, 09:42", status: "complete" },
        { label: "Compliance screening", timestamp: "Jul 19, 09:44", status: "complete" },
        { label: "Asset conversion", timestamp: "Jul 19, 09:47", status: "complete" },
        { label: "Bank payout initiated", timestamp: "Jul 19, 09:51", status: "current" },
        { label: "Settlement completed", timestamp: null, status: "upcoming" },
      ],
    },
    {
      id: "txn_10461",
      reference: "LNX-IT-10461",
      direction: "spot_to_funding",
      asset: "USDC",
      assetAmount: 25000,
      fiatCurrency: "USD",
      fiatAmount: 25000,
      feeUsd: 0,
      status: "completed",
      destination: "Funding wallet",
      createdAt: "2026-07-17T14:18:00.000Z",
      estimatedArrival: "Completed",
      timeline: [
        { label: "Transfer authorized", timestamp: "Jul 17, 14:18", status: "complete" },
        { label: "Funding wallet credited", timestamp: "Jul 17, 14:18", status: "complete" },
      ],
    },
    {
      id: "txn_10412",
      reference: "LNX-BW-10412",
      direction: "funding_to_bank",
      asset: "USDT",
      assetAmount: 8750,
      fiatCurrency: "GBP",
      fiatAmount: 6886.41,
      feeUsd: 45.63,
      status: "completed",
      destination: "Crownfield Bank •••• 1007",
      createdAt: "2026-07-11T11:03:00.000Z",
      estimatedArrival: "Completed Jul 12",
      timeline: [
        { label: "Request submitted", timestamp: "Jul 11, 11:03", status: "complete" },
        { label: "Compliance screening", timestamp: "Jul 11, 11:05", status: "complete" },
        { label: "Bank payout initiated", timestamp: "Jul 11, 11:11", status: "complete" },
        { label: "Settlement completed", timestamp: "Jul 12, 08:26", status: "complete" },
      ],
    },
    {
      id: "txn_10377",
      reference: "LNX-BW-10377",
      direction: "funding_to_bank",
      asset: "USDC",
      assetAmount: 50000,
      fiatCurrency: "USD",
      fiatAmount: 49810,
      feeUsd: 190,
      status: "review",
      destination: "Northstar Commercial •••• 4821",
      createdAt: "2026-07-06T16:32:00.000Z",
      estimatedArrival: "Compliance review",
      timeline: [
        { label: "Request submitted", timestamp: "Jul 6, 16:32", status: "complete" },
        { label: "Enhanced review", timestamp: "Jul 6, 16:34", status: "current" },
        { label: "Bank payout initiated", timestamp: null, status: "upcoming" },
        { label: "Settlement completed", timestamp: null, status: "upcoming" },
      ],
    },
  ],
};
